version: '2'
services:
  web:
    image: openjdk:alpine
    ports:
      - "8080:8080"
    links:
      - db 
    volumes:
      - .:/var/www/html   # I will share my code so I map this path
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./localDB:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
